import { Injectable } from '@angular/core';

import { FuncionarioEstado, FuncionarioListado } from '../interfaces/funcionario-listado.interface';

type FuncionarioDemo = [
  number,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  FuncionarioEstado,
];

@Injectable({ providedIn: 'root' })
export class FuncionariosDemoTableService {
  private readonly funcionarios: FuncionarioListado[] = (
    [
      [
        1,
        'Sistemas',
        '1002457891',
        'Ana Maria Rojas',
        'ana.rojas@correo.com',
        'Ingeniera de software',
        'Oficina de Tecnologia',
        'Bogota',
        'Activo',
      ],
      [
        2,
        'Producto',
        '1002457892',
        'Carlos Andres Perez',
        'carlos.perez@correo.com',
        'Gestor de producto',
        'Planeacion',
        'Medellin',
        'Activo',
      ],
      [
        3,
        'Analitica',
        '1002457893',
        'Juliana Torres',
        'juliana.torres@correo.com',
        'Analista de datos',
        'Analitica institucional',
        'Cali',
        'Pendiente',
      ],
      [
        4,
        'Diseno',
        '1002457894',
        'David Ramirez',
        'david.ramirez@correo.com',
        'Disenador UX/UI',
        'Comunicaciones',
        'Bogota',
        'Activo',
      ],
      [
        5,
        'Mercadeo',
        '1002457895',
        'Elena Castro',
        'elena.castro@correo.com',
        'Especialista de mercadeo',
        'Relacionamiento ciudadano',
        'Barranquilla',
        'Inactivo',
      ],
      [
        6,
        'Talento Humano',
        '1002457896',
        'Fernando Lopez',
        'fernando.lopez@correo.com',
        'Coordinador de talento humano',
        'Talento Humano',
        'Bogota',
        'Activo',
      ],
      [
        7,
        'Financiera',
        '1002457897',
        'Grace Mendoza',
        'grace.mendoza@correo.com',
        'Analista financiera',
        'Financiera',
        'Manizales',
        'Activo',
      ],
      [
        8,
        'Sistemas',
        '1002457898',
        'Henry Vargas',
        'henry.vargas@correo.com',
        'Desarrollador backend',
        'Oficina de Tecnologia',
        'Bogota',
        'Activo',
      ],
      [
        9,
        'Juridica',
        '1002457899',
        'Isabel Gomez',
        'isabel.gomez@correo.com',
        'Asesora juridica',
        'Juridica',
        'Pereira',
        'Pendiente',
      ],
      [
        10,
        'Logistica',
        '1002457900',
        'Juan Camilo Ortiz',
        'juan.ortiz@correo.com',
        'Lider operativo',
        'Logistica',
        'Cartagena',
        'Activo',
      ],
      [
        11,
        'Sistemas',
        '1002457901',
        'Karen Salazar',
        'karen.salazar@correo.com',
        'Analista QA',
        'Oficina de Tecnologia',
        'Bogota',
        'Activo',
      ],
      [
        12,
        'Planeacion',
        '1002457902',
        'Luis Herrera',
        'luis.herrera@correo.com',
        'Coordinador de proyectos',
        'Planeacion',
        'Tunja',
        'Inactivo',
      ],
      [
        13,
        'Financiera',
        '1002457903',
        'Maria Fernanda Diaz',
        'maria.diaz@correo.com',
        'Analista presupuestal',
        'Financiera',
        'Bucaramanga',
        'Activo',
      ],
      [
        14,
        'Comunicaciones',
        '1002457904',
        'Nicolas Cardenas',
        'nicolas.cardenas@correo.com',
        'Estratega de contenidos',
        'Comunicaciones',
        'Bogota',
        'Activo',
      ],
      [
        15,
        'Logistica',
        '1002457905',
        'Olga Martinez',
        'olga.martinez@correo.com',
        'Analista de suministros',
        'Logistica',
        'Santa Marta',
        'Pendiente',
      ],
      [
        16,
        'Sistemas',
        '1002457906',
        'Pablo Restrepo',
        'pablo.restrepo@correo.com',
        'Desarrollador frontend',
        'Oficina de Tecnologia',
        'Medellin',
        'Activo',
      ],
      [
        17,
        'Talento Humano',
        '1002457907',
        'Rachel Moreno',
        'rachel.moreno@correo.com',
        'Lider de seleccion',
        'Talento Humano',
        'Bogota',
        'Activo',
      ],
      [
        18,
        'Juridica',
        '1002457908',
        'Samuel Acosta',
        'samuel.acosta@correo.com',
        'Analista contractual',
        'Juridica',
        'Cucuta',
        'Activo',
      ],
      [
        19,
        'Planeacion',
        '1002457909',
        'Tatiana Pardo',
        'tatiana.pardo@correo.com',
        'Analista de procesos',
        'Planeacion',
        'Neiva',
        'Inactivo',
      ],
      [
        20,
        'Mercadeo',
        '1002457910',
        'Ulises Molina',
        'ulises.molina@correo.com',
        'Especialista digital',
        'Relacionamiento ciudadano',
        'Cali',
        'Activo',
      ],
      [
        21,
        'Financiera',
        '1002457911',
        'Valentina Ruiz',
        'valentina.ruiz@correo.com',
        'Lider contable',
        'Financiera',
        'Bogota',
        'Activo',
      ],
      [
        22,
        'Sistemas',
        '1002457912',
        'William Sanchez',
        'william.sanchez@correo.com',
        'Ingeniero DevOps',
        'Oficina de Tecnologia',
        'Medellin',
        'Pendiente',
      ],
      [
        23,
        'Logistica',
        '1002457913',
        'Ximena Arias',
        'ximena.arias@correo.com',
        'Coordinadora de flota',
        'Logistica',
        'Villavicencio',
        'Activo',
      ],
      [
        24,
        'Comunicaciones',
        '1002457914',
        'Yair Benitez',
        'yair.benitez@correo.com',
        'Enlace de prensa',
        'Comunicaciones',
        'Bogota',
        'Activo',
      ],
      [
        25,
        'Talento Humano',
        '1002457915',
        'Zoraida Pena',
        'zoraida.pena@correo.com',
        'Coordinadora de capacitacion',
        'Talento Humano',
        'Armenia',
        'Activo',
      ],
    ] satisfies FuncionarioDemo[]
  ).map(
    ([
      id,
      especialidad,
      identificacion,
      nombres,
      correo,
      cargo,
      dependencia,
      ubicacion,
      estado,
    ]) => ({
      id,
      especialidad,
      identificacion,
      nombres,
      correo,
      cargo,
      dependencia,
      ubicacion,
      estado,
    }),
  );

  getFuncionarios(): FuncionarioListado[] {
    return [...this.funcionarios];
  }
}
