import { Injectable } from '@angular/core';

import { FuncionarioListado } from '../interfaces/funcionario-listado.interface';

@Injectable({ providedIn: 'root' })
export class FuncionariosDemoTableService {
  private readonly funcionarios: FuncionarioListado[] = [
    {
      id: 1,
      especialidad: 'Sistemas',
      identificacion: '1002457891',
      name: 'Alice',
      email: 'alice@example.com',
      position: 'Software Engineer',
      company: 'ABC Company',
      country: 'United States',
      correo: 'alice@example.com',
      estado: 'Success',
    },
    {
      id: 2,
      especialidad: 'Producto',
      identificacion: '1002457892',
      name: 'Bob',
      email: 'bob@example.com',
      position: 'Product Manager',
      company: 'XYZ Inc',
      country: 'Canada',
      correo: 'bob@example.com',
      estado: 'Success',
    },
    {
      id: 3,
      especialidad: 'Analitica',
      identificacion: '1002457893',
      name: 'Charlie',
      email: 'charlie@example.com',
      position: 'Data Analyst',
      company: '123 Corp',
      country: 'Australia',
      correo: 'charlie@example.com',
      estado: 'Pending',
    },
    {
      id: 4,
      especialidad: 'Diseno',
      identificacion: '1002457894',
      name: 'David',
      email: 'david@example.com',
      position: 'UI/UX Designer',
      company: '456 Ltd',
      country: 'United Kingdom',
      correo: 'david@example.com',
      estado: 'Success',
    },
    {
      id: 5,
      especialidad: 'Mercadeo',
      identificacion: '1002457895',
      name: 'Eve',
      email: 'eve@example.com',
      position: 'Marketing Specialist',
      company: '789 Enterprises',
      country: 'France',
      correo: 'eve@example.com',
      estado: 'Inactive',
    },
    {
      id: 6,
      especialidad: 'Talento Humano',
      identificacion: '1002457896',
      name: 'Frank',
      email: 'frank@example.com',
      position: 'HR Manager',
      company: 'ABC Company',
      country: 'Germany',
      correo: 'frank@example.com',
      estado: 'Success',
    },
    {
      id: 7,
      especialidad: 'Financiera',
      identificacion: '1002457897',
      name: 'Grace',
      email: 'grace@example.com',
      position: 'Financial Analyst',
      company: 'XYZ Inc',
      country: 'Japan',
      correo: 'grace@example.com',
      estado: 'Success',
    },
    {
      id: 8,
      especialidad: 'Sistemas',
      identificacion: '1002457898',
      name: 'Henry',
      email: 'henry@example.com',
      position: 'Backend Developer',
      company: '123 Corp',
      country: 'Colombia',
      correo: 'henry@example.com',
      estado: 'Success',
    },
    {
      id: 9,
      especialidad: 'Juridica',
      identificacion: '1002457899',
      name: 'Isabel',
      email: 'isabel@example.com',
      position: 'Legal Advisor',
      company: '456 Ltd',
      country: 'Spain',
      correo: 'isabel@example.com',
      estado: 'Pending',
    },
    {
      id: 10,
      especialidad: 'Logistica',
      identificacion: '1002457900',
      name: 'John',
      email: 'john@example.com',
      position: 'Operations Lead',
      company: '789 Enterprises',
      country: 'Mexico',
      correo: 'john@example.com',
      estado: 'Success',
    },
    {
      id: 11,
      especialidad: 'Sistemas',
      identificacion: '1002457901',
      name: 'Karen',
      email: 'karen@example.com',
      position: 'QA Engineer',
      company: 'ABC Company',
      country: 'Chile',
      correo: 'karen@example.com',
      estado: 'Success',
    },
    {
      id: 12,
      especialidad: 'Planeacion',
      identificacion: '1002457902',
      name: 'Luis',
      email: 'luis@example.com',
      position: 'Project Coordinator',
      company: 'XYZ Inc',
      country: 'Peru',
      correo: 'luis@example.com',
      estado: 'Inactive',
    },
    {
      id: 13,
      especialidad: 'Financiera',
      identificacion: '1002457903',
      name: 'Maria',
      email: 'maria@example.com',
      position: 'Budget Analyst',
      company: '123 Corp',
      country: 'Brazil',
      correo: 'maria@example.com',
      estado: 'Success',
    },
    {
      id: 14,
      especialidad: 'Comunicaciones',
      identificacion: '1002457904',
      name: 'Nicolas',
      email: 'nicolas@example.com',
      position: 'Content Strategist',
      company: '456 Ltd',
      country: 'Italy',
      correo: 'nicolas@example.com',
      estado: 'Success',
    },
    {
      id: 15,
      especialidad: 'Logistica',
      identificacion: '1002457905',
      name: 'Olga',
      email: 'olga@example.com',
      position: 'Supply Analyst',
      company: '789 Enterprises',
      country: 'Portugal',
      correo: 'olga@example.com',
      estado: 'Pending',
    },
    {
      id: 16,
      especialidad: 'Sistemas',
      identificacion: '1002457906',
      name: 'Pablo',
      email: 'pablo@example.com',
      position: 'Frontend Developer',
      company: 'ABC Company',
      country: 'Argentina',
      correo: 'pablo@example.com',
      estado: 'Success',
    },
    {
      id: 17,
      especialidad: 'Talento Humano',
      identificacion: '1002457907',
      name: 'Rachel',
      email: 'rachel@example.com',
      position: 'Recruitment Lead',
      company: 'XYZ Inc',
      country: 'Uruguay',
      correo: 'rachel@example.com',
      estado: 'Success',
    },
    {
      id: 18,
      especialidad: 'Juridica',
      identificacion: '1002457908',
      name: 'Samuel',
      email: 'samuel@example.com',
      position: 'Contract Analyst',
      company: '123 Corp',
      country: 'Ecuador',
      correo: 'samuel@example.com',
      estado: 'Success',
    },
    {
      id: 19,
      especialidad: 'Planeacion',
      identificacion: '1002457909',
      name: 'Tatiana',
      email: 'tatiana@example.com',
      position: 'Business Analyst',
      company: '456 Ltd',
      country: 'Panama',
      correo: 'tatiana@example.com',
      estado: 'Inactive',
    },
    {
      id: 20,
      especialidad: 'Mercadeo',
      identificacion: '1002457910',
      name: 'Ulises',
      email: 'ulises@example.com',
      position: 'Digital Specialist',
      company: '789 Enterprises',
      country: 'Costa Rica',
      correo: 'ulises@example.com',
      estado: 'Success',
    },
    {
      id: 21,
      especialidad: 'Financiera',
      identificacion: '1002457911',
      name: 'Valentina',
      email: 'valentina@example.com',
      position: 'Accounting Lead',
      company: 'ABC Company',
      country: 'United States',
      correo: 'valentina@example.com',
      estado: 'Success',
    },
    {
      id: 22,
      especialidad: 'Sistemas',
      identificacion: '1002457912',
      name: 'William',
      email: 'william@example.com',
      position: 'DevOps Engineer',
      company: 'XYZ Inc',
      country: 'Canada',
      correo: 'william@example.com',
      estado: 'Pending',
    },
    {
      id: 23,
      especialidad: 'Logistica',
      identificacion: '1002457913',
      name: 'Ximena',
      email: 'ximena@example.com',
      position: 'Fleet Coordinator',
      company: '123 Corp',
      country: 'Australia',
      correo: 'ximena@example.com',
      estado: 'Success',
    },
    {
      id: 24,
      especialidad: 'Comunicaciones',
      identificacion: '1002457914',
      name: 'Yair',
      email: 'yair@example.com',
      position: 'Press Officer',
      company: '456 Ltd',
      country: 'United Kingdom',
      correo: 'yair@example.com',
      estado: 'Success',
    },
    {
      id: 25,
      especialidad: 'Talento Humano',
      identificacion: '1002457915',
      name: 'Zoraida',
      email: 'zoraida@example.com',
      position: 'Training Coordinator',
      company: '789 Enterprises',
      country: 'France',
      correo: 'zoraida@example.com',
      estado: 'Success',
    },
  ];

  /** Entrega datos de ejemplo para la plantilla visual; puede reemplazarse por una llamada HTTP. */
  getFuncionarios(): FuncionarioListado[] {
    return [...this.funcionarios];
  }
}
