import { Injectable } from '@angular/core';

import { FuncionarioListado } from '../interfaces/funcionario-listado.interface';

@Injectable({ providedIn: 'root' })
export class FuncionariosDemoTableService {
  private readonly funcionarios: FuncionarioListado[] = [
    {
      id: 1,
      especialidad: 'Sistemas',
      identificacion: '1002457891',
      nombresApellidos: 'Alice Martinez Rojas',
      correo: 'alice.martinez@example.com',
      cargo: 'Software Engineer',
      unidad: 'ABC Company',
      estado: 'Activo',
    },
    {
      id: 2,
      especialidad: 'Talento Humano',
      identificacion: '1002457892',
      nombresApellidos: 'Bob Ramirez Gomez',
      correo: 'bob.ramirez@example.com',
      cargo: 'Product Manager',
      unidad: 'XYZ Inc',
      estado: 'Activo',
    },
    {
      id: 3,
      especialidad: 'Planeacion',
      identificacion: '1002457893',
      nombresApellidos: 'Charlie Diaz Torres',
      correo: 'charlie.diaz@example.com',
      cargo: 'Data Analyst',
      unidad: '123 Corp',
      estado: 'Novedad',
    },
    {
      id: 4,
      especialidad: 'Comunicaciones',
      identificacion: '1002457894',
      nombresApellidos: 'David Castro Pena',
      correo: 'david.castro@example.com',
      cargo: 'UI/UX Designer',
      unidad: '456 Ltd',
      estado: 'Activo',
    },
    {
      id: 5,
      especialidad: 'Mercadeo',
      identificacion: '1002457895',
      nombresApellidos: 'Eve Sanchez Mora',
      correo: 'eve.sanchez@example.com',
      cargo: 'Marketing Specialist',
      unidad: '789 Enterprises',
      estado: 'Inactivo',
    },
    {
      id: 6,
      especialidad: 'Talento Humano',
      identificacion: '1002457896',
      nombresApellidos: 'Frank Moreno Gil',
      correo: 'frank.moreno@example.com',
      cargo: 'HR Manager',
      unidad: 'ABC Company',
      estado: 'Activo',
    },
    {
      id: 7,
      especialidad: 'Financiera',
      identificacion: '1002457897',
      nombresApellidos: 'Grace Navarro Ruiz',
      correo: 'grace.navarro@example.com',
      cargo: 'Financial Analyst',
      unidad: 'XYZ Inc',
      estado: 'Activo',
    },
    {
      id: 8,
      especialidad: 'Sistemas',
      identificacion: '1002457898',
      nombresApellidos: 'Hector Parra Leon',
      correo: 'hector.parra@example.com',
      cargo: 'Backend Developer',
      unidad: '123 Corp',
      estado: 'Activo',
    },
    {
      id: 9,
      especialidad: 'Juridica',
      identificacion: '1002457899',
      nombresApellidos: 'Isabel Ortega Vargas',
      correo: 'isabel.ortega@example.com',
      cargo: 'Legal Advisor',
      unidad: '456 Ltd',
      estado: 'Novedad',
    },
    {
      id: 10,
      especialidad: 'Logistica',
      identificacion: '1002457900',
      nombresApellidos: 'Juan Herrera Soto',
      correo: 'juan.herrera@example.com',
      cargo: 'Operations Lead',
      unidad: '789 Enterprises',
      estado: 'Activo',
    },
    {
      id: 11,
      especialidad: 'Sistemas',
      identificacion: '1002457901',
      nombresApellidos: 'Karen Luna Mejia',
      correo: 'karen.luna@example.com',
      cargo: 'QA Engineer',
      unidad: 'ABC Company',
      estado: 'Activo',
    },
    {
      id: 12,
      especialidad: 'Planeacion',
      identificacion: '1002457902',
      nombresApellidos: 'Luis Cardenas Arias',
      correo: 'luis.cardenas@example.com',
      cargo: 'Project Coordinator',
      unidad: 'XYZ Inc',
      estado: 'Inactivo',
    },
    {
      id: 13,
      especialidad: 'Financiera',
      identificacion: '1002457903',
      nombresApellidos: 'Maria Pardo Soler',
      correo: 'maria.pardo@example.com',
      cargo: 'Budget Analyst',
      unidad: '123 Corp',
      estado: 'Activo',
    },
    {
      id: 14,
      especialidad: 'Comunicaciones',
      identificacion: '1002457904',
      nombresApellidos: 'Nicolas Rios Cano',
      correo: 'nicolas.rios@example.com',
      cargo: 'Content Strategist',
      unidad: '456 Ltd',
      estado: 'Activo',
    },
    {
      id: 15,
      especialidad: 'Logistica',
      identificacion: '1002457905',
      nombresApellidos: 'Olga Vargas Nino',
      correo: 'olga.vargas@example.com',
      cargo: 'Supply Analyst',
      unidad: '789 Enterprises',
      estado: 'Novedad',
    },
    {
      id: 16,
      especialidad: 'Sistemas',
      identificacion: '1002457906',
      nombresApellidos: 'Pablo Gomez Bernal',
      correo: 'pablo.gomez@example.com',
      cargo: 'Frontend Developer',
      unidad: 'ABC Company',
      estado: 'Activo',
    },
    {
      id: 17,
      especialidad: 'Talento Humano',
      identificacion: '1002457907',
      nombresApellidos: 'Raquel Molina Paz',
      correo: 'raquel.molina@example.com',
      cargo: 'Recruitment Lead',
      unidad: 'XYZ Inc',
      estado: 'Activo',
    },
    {
      id: 18,
      especialidad: 'Juridica',
      identificacion: '1002457908',
      nombresApellidos: 'Samuel Acosta Vera',
      correo: 'samuel.acosta@example.com',
      cargo: 'Contract Analyst',
      unidad: '123 Corp',
      estado: 'Activo',
    },
    {
      id: 19,
      especialidad: 'Planeacion',
      identificacion: '1002457909',
      nombresApellidos: 'Tatiana Salazar Rey',
      correo: 'tatiana.salazar@example.com',
      cargo: 'Business Analyst',
      unidad: '456 Ltd',
      estado: 'Inactivo',
    },
    {
      id: 20,
      especialidad: 'Mercadeo',
      identificacion: '1002457910',
      nombresApellidos: 'Ulises Romero Casas',
      correo: 'ulises.romero@example.com',
      cargo: 'Digital Specialist',
      unidad: '789 Enterprises',
      estado: 'Activo',
    },
    {
      id: 21,
      especialidad: 'Financiera',
      identificacion: '1002457911',
      nombresApellidos: 'Valentina Suarez Mora',
      correo: 'valentina.suarez@example.com',
      cargo: 'Accounting Lead',
      unidad: 'ABC Company',
      estado: 'Activo',
    },
    {
      id: 22,
      especialidad: 'Sistemas',
      identificacion: '1002457912',
      nombresApellidos: 'William Rojas Cely',
      correo: 'william.rojas@example.com',
      cargo: 'DevOps Engineer',
      unidad: 'XYZ Inc',
      estado: 'Novedad',
    },
    {
      id: 23,
      especialidad: 'Logistica',
      identificacion: '1002457913',
      nombresApellidos: 'Ximena Fuentes Rico',
      correo: 'ximena.fuentes@example.com',
      cargo: 'Fleet Coordinator',
      unidad: '123 Corp',
      estado: 'Activo',
    },
    {
      id: 24,
      especialidad: 'Comunicaciones',
      identificacion: '1002457914',
      nombresApellidos: 'Yair Medina Silva',
      correo: 'yair.medina@example.com',
      cargo: 'Press Officer',
      unidad: '456 Ltd',
      estado: 'Activo',
    },
    {
      id: 25,
      especialidad: 'Talento Humano',
      identificacion: '1002457915',
      nombresApellidos: 'Zoraida Benitez Melo',
      correo: 'zoraida.benitez@example.com',
      cargo: 'Training Coordinator',
      unidad: '789 Enterprises',
      estado: 'Activo',
    },
  ];

  /** Entrega datos de ejemplo para la plantilla visual; puede reemplazarse por una llamada HTTP. */
  getFuncionarios(): FuncionarioListado[] {
    return [...this.funcionarios];
  }
}
